neo4j:
  url: 'neo4j://127.0.0.1:7687'
  user: 'neo4j'
  password: '231099'
  file: 'data/2021-11-19 Roder связи.xlsx'
  new_url: 'neo4j://127.0.0.1:7688'
  new_user: 'neo4j'
  new_password: '231099'
  last_url: 'neo4j+s://99c1a702.databases.neo4j.io:7687'